spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/gestorpro
spring.datasource.username=gestorpro
spring.datasource.password=gestorpro_local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
