-- Execute dentro do psql. A tabela de treino fica separada da API.
CREATE TABLE IF NOT EXISTS fornecedores_treino (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cnpj VARCHAR(255),
    categoria VARCHAR(255),
    telefone VARCHAR(255)
);

INSERT INTO fornecedores_treino (nome, cnpj, categoria, telefone)
VALUES ('TechDistrib', '12.345.678/0001-90', 'Eletrônicos', '(83) 3333-1000')
RETURNING id;

SELECT * FROM fornecedores_treino ORDER BY id;
-- Nos próximos comandos, troque 1 pelo ID que o INSERT devolveu.
SELECT * FROM fornecedores_treino WHERE id = 1;
UPDATE fornecedores_treino SET telefone = '(83) 3333-2000' WHERE id = 1;
SELECT * FROM fornecedores_treino WHERE id = 1;
DELETE FROM fornecedores_treino WHERE id = 1;
SELECT * FROM fornecedores_treino WHERE id = 1;
